[Configuration]
name = "My Configuration"

  [[Room]]
    Name="Room1"

    [[Room.Rack]]
      Name = "Rack1"

      [[Room.Rack.Crate]]
        Name = "Crate1"

        [[Room.Rack.Crate.Board]]
          Name = "V1742"
          Type = "V1742"
          Slot = 5
          # WRITE_REGISTER: generic write register access. This command allows the user to have a direct write access
          # to the registers of the board. NOTE: all the direct write accesses are executed AFTER the other settings,
          # thus it might happen that the direct write overwrites a specific setting.
          # To avoid this use the right "MASK".
          # Syntax: WRITE_REGISTER ADDRESS DATA MASK, where ADDRESS is the address offset of the register (16 bit hex), DATA
          # is the value being written (32 bit hex) and MASK is the bitmask to be used for DATA masking.
          # Example: Set only bit [8] of register 1080 to 1, leaving the other bits to their previous value
          # WRITE_REGISTER=[[1080,0100,0100]]
          # Example: Set only bit [8] of register 1080 to 0, leaving the other bits to their previous value
          # WRITE_REGISTER [[1080,0000,0100]]
          # Example: Set register 1080 to the value of 0x45:
          # WRITE_REGISTER [[1080,45,FFFFFFFF]]
          #WRITE_REGISTER=[[0,1,2],[3,4,5],[6,7,8]]
          # RECORD_LENGTH = number of samples in the acquisition window
          # For 742 family the options available are only 1024, 520, 256 and 136
          RECORD_LENGTH = 1024
          # DECIMATION_FACTOR: ONLY FOR 740 and 724 MODELS. change the decimation factor for the acquisition.
          # Options: 1 2 4 8 16 32 64 128
          DECIMATION_FACTOR =1
          # POST_TRIGGER: post trigger size in percent of the whole acquisition window
          # options: 0 to 100
          # For x742 there is a delay of about 42 nsec on Fast Trigger TR, and about 115 nsec on TRG-IN;
          # the post trigger is added to this delay
          POST_TRIGGER=1
          # EXTERNAL_TRIGGER: external trigger input settings. When enabled, the ext. trg. can be either
          # propagated (ACQUISITION_AND_TRGOUT) or not (ACQ_ONLY) through the TRGOUT
          # options: DISABLED, ACQ_ONLY, ACQUISITION_AND_TRGOUT
          EXTERNAL_TRIGGER ="ACQ_ONLY"
          # FPIO_LEVEL: type of the front panel I/O LEMO connectors
          # options: NIM, TTL
          FPIO_LEVEL="NIM"
          # TEST_PATTERN: if enabled, data from ADC are replaced by test pattern (triangular wave)
          # options: true, false
          TEST_PATTERN=false
          # FAST_TRIGGER: fast trigger input settings. ONLY FOR 742 MODELS. When enabled, the fast trigger is used
          # for the data acquisition
          # options: DISABLED, ACQ_ONLY
          FAST_TRIGGER="ACQ_ONLY"
          # OUTPUT_FILE_HEADER: if enabled, the header is included in the output file data
          # options: true, false
          #OUTPUT_FILE_HEADER=true
          # OUTPUT_FILE_FORMAT: output file can be either ASCII (column of decimal numbers) or binary
          # (2 bytes per sample, except for Mod 721 and Mod 731 that is 1 byte per sample)
          # options: BINARY, ASCII, ROOT
          #OUTPUT_FILE_FORMAT="ROOT"
          # Set the DRS4 Chip Frequency (for X742 boards only)
          # Values: 5GHz, 2.5 GHz ,1GHz ,750MHz
          DRS4_FREQUENCY="5GHz"
          #PULSE_POLARITY: input signal polarity.
          #options: POSITIVE, NEGATIVE
          PULSE_POLARITY="NEGATIVE"
          # FAST_TRIGGER_DIGITIZING: ONLY FOR 742 MODELS. If enabled the fast trigger signal is digitized and it is
          # present in data readout as channel n.8 for each group.
          # options: true, false
          ENABLED_FAST_TRIGGER_DIGITIZING=true
          #Interrupt settings (request interrupt when there are at least N events to
          #read; 0=disable interrupts (polling mode))
          USE_INTERRUPT=0
          #Skip startup calibration
          SKIP_STARTUP_CALIBRATION=false
          #Max. number of events for a block transfer (0 to 1023)
          MAX_NUM_EVENTS_BLT=1023

          # ----------------------------------------------------------------
          # Custom Setting for Model 742
          # ----------------------------------------------------------------
          # FAST TRIGGER CONDITION SETTINGS.
          # Remember that signal TR0 is the Fast Trigger for Groups 0 and 1, while signal TR1 is the Fast Trigger for Groups 2 and 3.
          # DC_OFFSET_TR*: DC offset adjust is DAC setting: 0 to 65535
          # TRIGGER_THRESHOLD_TR*: Trigger Threshold is the DAC setting for the comparation level: 0 to 65535

          # EXAMPLES pcb rev0 (see also User's Manual):
          # NIM signal on TR
          # 	DC_OFFSET_TR* 4096
          #  	TRIGGER_THRESHOLD_TR* 29053
          # AC signal on TR
          # 	DC_OFFSET_TR* 4096
          #  	TRIGGER_THRESHOLD_TR* 27776
          # TTL signal on TR
          # 	DC_OFFSET_TR* 16384
          # 	TRIGGER_THRESHOLD_TR* 29016

          # EXAMPLES pcb rev1 (see also User's Manual):
          # NIM signal on TR
          # 	DC_OFFSET_TR* 32768
          #   TRIGGER_THRESHOLD_TR* 20934
          # AC signal on TR
          # 	DC_OFFSET_TR* 32768
          #  	TRIGGER_THRESHOLD_TR* 26214
          # +2V signal on TR
          # 	DC_OFFSET_TR* 43520
          # 	TRIGGER_THRESHOLD_TR* 26214
          DC_OFFSET_TR0=32768
          TRIGGER_THRESHOLD_TR0=20934
          DC_OFFSET_TR1=32768
          TRIGGER_THRESHOLD_TR1=20934
          GRP0_CH_DC_OFFSET="4,4,4,4,4,4,4,4" #0-4096 1.12V
          [Room.Rack.Crate.Board.Connector]
            Name = "Connector1"
            "Connection Type" = "USB"
            "VME Base Address"=0x32110000
            Type = "CAENDigitizer"
            Model = "V1718"
            "Link Number" = 0

[[Room.Rack.Crate.Board]]
Slot = 0
Name="HV"
Type="Wiener"

[Room.Rack.Crate.Board.Connector]
Name = "SNMP_WIENER"
Type = "SNMP"
IP = "192.168.0.230"
MIB_path = "/home/rpclab/Desktop/Tests/extras/WIENER/data"
MIB_filename = "WIENER-CRATE-MIB"
"Retries"= 3
"Version"= "v2c"
"ReadCommunity" = "guru"

