# IXWebSocket
set(IXWebSocket_repository "https://github.com/RPClab/IXWebSocket.git")
set(IXWebSocket_version "master")
# CAENlibs
set(CAENlibs_repository "https://github.com/RPClab/CAENlibs.git")
set(CAENlibs_version "master")
# elogpp
set(elogpp_repository "https://github.com/RPClab/elogpp.git")
set(elogpp_version "master")
# doctest
set(doctest_repository "https://github.com/onqtam/doctest.git")
set(doctest_version "master")
