# IXWebSocket
set(IXWebSocket_repository "https://github.com/RPClab/IXWebSocket.git")
set(IXWebSocket_version "master")
# CAENlibs
set(CAENlibs_repository "https://github.com/RPClab/CAENlibs.git")
set(CAENlibs_version "master")
# elogpp
set(elogpp_repository "https://github.com/RPClab/elogpp.git")
set(elogpp_version "master")
# doctest
set(doctest_repository "https://github.com/onqtam/doctest.git")
set(doctest_version "master")
# fmt
set(fmt_repository "https://github.com/RPClab/fmt.git")
set(fmt_version "master")
# fmt
set(CLI11_repository "https://github.com/RPClab/CLI11.git")
set(CLI11_version "master")
