# IXWebSocket
set(IXWebSocket_repository "https://github.com/machinezone/IXWebSocket.git")
set(IXWebSocket_version "master")
# CAENlibs
set(CAENlibs_repository "https://github.com/RPClab/CAENlibs.git")
set(CAENlibs_version "master")
# elogpp
set(elogpp_repository "https://github.com/RPClab/elogpp.git")
set(elogpp_version "master")
# doctest
set(doctest_repository "https://github.com/onqtam/doctest.git")
set(doctest_version "master")
# fmt
set(fmt_repository "https://github.com/RPClab/fmt.git")
set(fmt_version "master")
# CLI11
set(CLI11_repository "https://github.com/RPClab/CLI11.git")
set(CLI11_version "master")
# soci
set(soci_repository "https://github.com/RPClab/soci.git")
set(soci_version "master")
# toml11
set(toml11_repository "https://github.com/RPClab/toml11.git")
set(toml11_version "master")
# spdlog
set(spdlog_repository "https://github.com/RPClab/spdlog.git")
set(spdlog_version "v1.x")
