#pragma once

#include "Internal.hpp"

enum class StatusCode : int_least32_t
{
  SUCCESS = 0,
  FAILURE,
  NOT_FOUND,
  NOT_INITIALIZED,
  INVALID_CONVERSION,
  ALREADY_INITIALIZED,
  OUT_OF_RANGE,
  NOT_ALLOWED,
  INVALID_PARAMETER,
  UNCHANGED,
  INVALID_PTR,
  JSON_PARSING,
  WRONG_NUMBER_PARAMETERS,
  ALREADY_PRESENT = 5000,
};
