#pragma once

enum class StatusCode : std::int16_t
{
  SUCCESS = 1,
  FAILURE,
  NOT_FOUND,
  NOT_INITIALIZED,
  ALREADY_INITIALIZED,
  OUT_OF_RANGE,
  NOT_ALLOWED,
  INVALID_PARAMETER,
  UNCHANGED,
  INVALID_PTR,
  JSON_PARSING,
  WRONG_NUMBER_PARAMETERS,
  ALREADY_PRESENT = 5000,
};
