name: 'Windows MSVC'

env:
  CMAKE_VERSION: '3.16.x'
  CMAKE_BUILD_TYPE: 'Release'
  CMAKE_BUILD_PREFIX: './build'

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    name: '🚧 🟨 MSVC'

    steps:

    - name: '🧰 Checkout'
      uses: actions/checkout@v4.1.1

    - name: '🟨 Setup CMake'
      uses: jwlawson/actions-setup-cmake@v1.14
      with:
        cmake-version: '${{env.CMAKE_VERSION}}'
        github-api-token: ${{ secrets.GITHUB_TOKEN }}

    - name: '🟨 Setup Visual Studio'
      uses: ilammy/msvc-dev-cmd@v1.13.0

    - name: '${{ matrix.icon }} Cache ROOT'
      uses: actions/cache@v3.3.3
      with:
        path: '${{ env.CMAKE_BUILD_PREFIX }}/_deps/root-build'
        key: 'root'

    - name: '🔧 Configure'
      run: cmake -S ${{ github.workspace }} -B ${{ env.CMAKE_BUILD_PREFIX }} -Thost=x64

    - name: '⚙️ Build'
      run: cmake --build ${{ env.CMAKE_BUILD_PREFIX }} --config ${{ env.CMAKE_BUILD_TYPE }} --parallel 2

    - name: '🧪 Run tests'
      working-directory: ${{ env.CMAKE_BUILD_PREFIX }}
      run: ctest -C ${{ env.CMAKE_BUILD_TYPE }} -j2 -VV --output-on-failure
